import Mathlib.Algebra.MvPolynomial.Eval

/-!
# Polynomial actions generated by a commuting family of endomorphisms

The target of `MvPolynomial.aeval` is required to be commutative.  A family of
pairwise commuting endomorphisms therefore gives an evaluation map by first
landing in the commutative subalgebra which it generates.
-/

open scoped IsMulCommutative

namespace AlgebraicAnalysis.CommutingPolynomialAction

universe u v w z

variable {k : Type u} [CommRing k]
variable {V : Type v} [AddCommGroup V] [Module k V]

private theorem range_commutative (v : σ → Module.End k V)
    (hcomm : ∀ i j, Commute (v i) (v j)) :
    ∀ x ∈ Set.range v, ∀ y ∈ Set.range v, x * y = y * x := by
  rintro _ ⟨i, rfl⟩ _ ⟨j, rfl⟩
  exact (hcomm i j).eq

/-- Evaluation of multivariate polynomials at a pairwise commuting family of
endomorphisms. -/
noncomputable def commutingPolynomialAction {σ : Type w}
    (v : σ → Module.End k V)
    (hcomm : ∀ i j, Commute (v i) (v j)) :
    MvPolynomial σ k →ₐ[k] Module.End k V := by
  let S : Subalgebra k (Module.End k V) := Algebra.adjoin k (Set.range v)
  letI : IsMulCommutative S :=
    Algebra.isMulCommutative_adjoin k (range_commutative v hcomm)
  exact
    (S.val).comp
      (MvPolynomial.aeval (fun i =>
        ⟨v i, Algebra.subset_adjoin ⟨i, rfl⟩⟩))

@[simp] theorem commutingPolynomialAction_apply_X {σ : Type w}
    (v : σ → Module.End k V) (hcomm : ∀ i j, Commute (v i) (v j)) (i : σ) :
    commutingPolynomialAction v hcomm (MvPolynomial.X i) = v i := by
  classical
  simp [commutingPolynomialAction]

/-- Evaluation sends constants to scalar endomorphisms. This named
compatibility lemma is retained even though generic algebra-hom simplification
can also discharge its left-hand side. -/
@[simp, nolint simpNF] theorem commutingPolynomialAction_apply_C {σ : Type w}
    (v : σ → Module.End k V) (hcomm : ∀ i j, Commute (v i) (v j)) (a : k) :
    commutingPolynomialAction v hcomm (MvPolynomial.C a) = algebraMap k (Module.End k V) a := by
  classical
  simp [commutingPolynomialAction]

theorem commutingPolynomialAction_intertwines {σ : Type w}
    {W : Type z} [AddCommGroup W] [Module k W]
    (v : σ → Module.End k V) (w : σ → Module.End k W)
    (hv : ∀ i j, Commute (v i) (v j))
    (hw : ∀ i j, Commute (w i) (w j))
    (f : V →ₗ[k] W)
    (hgen : ∀ i, f.comp (v i) = (w i).comp f) (p : MvPolynomial σ k) :
    f.comp (commutingPolynomialAction v hv p) =
      (commutingPolynomialAction w hw p).comp f := by
  classical
  induction p using MvPolynomial.induction_on with
  | C a =>
      apply LinearMap.ext
      intro x
      simp only [LinearMap.comp_apply, commutingPolynomialAction_apply_C]
      change f (a • x) = a • f x
      exact f.map_smul a x
  | add p q hp hq =>
      rw [map_add, map_add, LinearMap.comp_add, LinearMap.add_comp, hp, hq]
  | mul_X p i hp =>
      apply LinearMap.ext
      intro x
      simp only [map_mul, LinearMap.comp_apply, Module.End.mul_apply,
        commutingPolynomialAction_apply_X]
      calc
        f ((commutingPolynomialAction v hv p) (v i x)) =
            (commutingPolynomialAction w hw p) (f (v i x)) :=
          congrArg (fun g : V →ₗ[k] W => g (v i x)) hp
        _ = (commutingPolynomialAction w hw p) (w i (f x)) := by
          have hgi := congrArg (fun g : V →ₗ[k] W => g x) (hgen i)
          change f (v i x) = w i (f x) at hgi
          rw [hgi]

/-- The polynomial action as a module structure on the original space. -/
noncomputable def commutingPolynomialModule {σ : Type w}
    (v : σ → Module.End k V) (hcomm : ∀ i j, Commute (v i) (v j)) :
    Module (MvPolynomial σ k) V :=
  Module.compHom V (commutingPolynomialAction v hcomm).toRingHom

end AlgebraicAnalysis.CommutingPolynomialAction
