import Mathlib

/-!
# Unimodular elements and a free rank-one summand

This file contains the unconditional module-theoretic splitting associated
to a unimodular element.  It uses no rank, Ore, simplicity, or finiteness
hypothesis.
-/

namespace AlgebraicAnalysis.Unimodular

variable {R N : Type*} [Ring R] [AddCommGroup N] [Module R N]

/-- An element of a left module is unimodular if a left-linear functional
 takes it to `1`. -/
def IsUnimodular (x : N) : Prop := ∃ φ : N →ₗ[R] R, φ x = 1

theorem exists_unimodular_iff_surjective :
    (∃ x : N, IsUnimodular (R := R) x) ↔
      ∃ φ : N →ₗ[R] R, Function.Surjective φ := by
  constructor
  · rintro ⟨x, φ, hφ⟩
    exact ⟨φ, fun r ↦ by
      refine ⟨r • x, ?_⟩
      rw [φ.map_smul, hφ, smul_eq_mul, mul_one]
      ⟩
  · rintro ⟨φ, hφ⟩
    obtain ⟨x', hx'⟩ := hφ 1
    exact ⟨x', φ, hx'⟩

/-- The projection onto the kernel of a functional which is normalized at
 `x`. -/
def unimodularKernelProjection (φ : N →ₗ[R] R) (x : N)
    (hx : φ x = 1) : N →ₗ[R] LinearMap.ker φ :=
  (LinearMap.id - (LinearMap.toSpanSingleton R N x).comp φ).codRestrict
    (LinearMap.ker φ) (by
      intro y
      rw [LinearMap.mem_ker]
      simp only [LinearMap.sub_apply, LinearMap.id_apply, LinearMap.coe_comp,
        Function.comp_apply, LinearMap.toSpanSingleton_apply]
      rw [φ.map_sub, φ.map_smul, hx, smul_eq_mul, mul_one, sub_self])

/-- The canonical splitting map associated to a normalized functional. -/
def unimodularSplitMap (φ : N →ₗ[R] R) (x : N) (hx : φ x = 1) :
    N →ₗ[R] LinearMap.ker φ × R :=
  (unimodularKernelProjection φ x hx).prod φ

/-- The inverse map to `unimodularSplitMap`. -/
def unimodularSplitMapInv (φ : N →ₗ[R] R) (x : N) :
    LinearMap.ker φ × R →ₗ[R] N :=
  { toFun := fun y ↦ y.1.1 + y.2 • x
    map_add' := by
      intro y z
      simp only [Prod.fst_add, Prod.snd_add, Submodule.coe_add, add_smul]
      abel
    map_smul' := by
      intro r y
      simp only [Prod.smul_mk, Submodule.coe_smul]
      simp [smul_add, mul_smul]
    }

theorem unimodularSplitMap_left_inverse
    (φ : N →ₗ[R] R) (x : N) (hx : φ x = 1) :
    (unimodularSplitMapInv φ x).comp (unimodularSplitMap φ x hx) =
      LinearMap.id := by
  apply LinearMap.ext
  intro y
  dsimp [unimodularSplitMap, unimodularSplitMapInv,
    unimodularKernelProjection]
  change (y - φ y • x) + φ y • x = y
  exact sub_add_cancel _ _

theorem unimodularSplitMap_right_inverse
    (φ : N →ₗ[R] R) (x : N) (hx : φ x = 1) :
    (unimodularSplitMap φ x hx).comp (unimodularSplitMapInv φ x) =
      LinearMap.id := by
  apply LinearMap.ext
  rintro ⟨y, r⟩
  dsimp [unimodularSplitMap, unimodularSplitMapInv,
    unimodularKernelProjection]
  apply Prod.ext
  · apply Subtype.ext
    change y.1 + r • x - φ (y.1 + r • x) • x = y.1
    rw [φ.map_add, φ.map_smul, LinearMap.mem_ker.mp y.2]
    simp [hx, smul_eq_mul]
  · simp only [LinearMap.comp_apply, unimodularSplitMap, LinearMap.prod_apply,
      unimodularSplitMapInv, LinearMap.map_add, LinearMap.map_smul,
      smul_eq_mul, mul_one, add_zero]
    rw [LinearMap.mem_ker.mp y.2, zero_add, hx]
    exact mul_one r

/-- A unimodular element splits off a free rank-one factor. -/
def unimodularSplitEquiv (φ : N →ₗ[R] R) (x : N) (hx : φ x = 1) :
    N ≃ₗ[R] LinearMap.ker φ × R :=
  LinearEquiv.ofLinear (unimodularSplitMap φ x hx)
    (unimodularSplitMapInv φ x)
    (unimodularSplitMap_right_inverse φ x hx)
    (unimodularSplitMap_left_inverse φ x hx)

theorem unimodular_split (x : N) (hx : IsUnimodular (R := R) x) :
    ∃ φ : N →ₗ[R] R, ∃ _hφ : φ x = 1,
    Nonempty (N ≃ₗ[R] LinearMap.ker φ × R) := by
  obtain ⟨φ, hφ⟩ := hx
  exact ⟨φ, hφ, ⟨unimodularSplitEquiv φ x hφ⟩⟩

/-- The cyclic submodule generated by a unimodular element is a free
 rank-one module.  The target is the actual range, so no commutativity or
 centrality assumption on `R` is hidden in the statement. -/
theorem unimodular_span_singleton_free (x : N)
    (hx : IsUnimodular (R := R) x) :
    Module.Free R (LinearMap.range (LinearMap.toSpanSingleton R N x)) := by
  obtain ⟨φ, hφ⟩ := hx
  let e : R ≃ₗ[R] LinearMap.range (LinearMap.toSpanSingleton R N x) :=
    LinearEquiv.ofInjective (LinearMap.toSpanSingleton R N x) (by
      intro r s hrs
      change r • x = s • x at hrs
      have hzero : (r - s) • x = 0 := by
        rw [sub_smul, hrs, sub_self]
      have hzero' := congrArg φ hzero
      have hrs' : r - s = 0 := by
        simpa [φ.map_smul, hφ, smul_eq_mul] using hzero'
      exact sub_eq_zero.mp hrs')
  exact Module.Free.of_equiv e

/-- The kernel of a split functional is a direct summand of its domain.  In
 particular, if the domain is projective then this kernel is projective. -/
theorem projective_ker_of_unimodular
    [Module.Projective R N] (φ : N →ₗ[R] R) (x : N) (hx : φ x = 1) :
    Module.Projective R (LinearMap.ker φ) := by
  apply Module.Projective.of_split (LinearMap.ker φ).subtype
    (unimodularKernelProjection φ x hx)
  apply LinearMap.ext
  intro y
  apply Subtype.ext
  dsimp [unimodularKernelProjection]
  rw [LinearMap.mem_ker.mp y.2, zero_smul, sub_zero]

#print axioms exists_unimodular_iff_surjective
#print axioms unimodularSplitMap_left_inverse
#print axioms unimodularSplitMap_right_inverse
#print axioms unimodular_split
#print axioms unimodular_span_singleton_free
#print axioms projective_ker_of_unimodular

end AlgebraicAnalysis.Unimodular
