import Mathlib.Algebra.MvPolynomial.Variables
import Mathlib.RingTheory.Ideal.Prime
import Mathlib.RingTheory.MvPolynomial.Homogeneous
import Mathlib.RingTheory.MvPolynomial.Ideal

/-!
# A distinguished variable in a homogeneous prime relation

If a homogeneous polynomial uses one distinguished variable together with a
set of auxiliary variables, then subtracting its pure distinguished monomial
puts it in the ideal generated by the auxiliary variables.  Consequently, a
prime containing the polynomial and every auxiliary variable also contains
the distinguished variable, provided the pure coefficient is a unit.
-/

namespace AlgebraicAnalysis.MvPolynomial

open scoped BigOperators

variable {R σ : Type*} [CommRing R]

/-- Removing the pure distinguished monomial from a homogeneous polynomial
leaves an element of the ideal generated by its other allowed variables. -/
theorem sub_pureMonomial_mem_span_X
    {P : MvPolynomial σ R} {N : ℕ} {t : σ} {s : Set σ} {c : R}
    (hP : P.IsHomogeneous N)
    (hvars : (P.vars : Set σ) ⊆ insert t s)
    (hcoeff : P.coeff (Finsupp.single t N) = c) :
    P - MvPolynomial.monomial (Finsupp.single t N) c ∈
      Ideal.span (MvPolynomial.X '' s : Set (MvPolynomial σ R)) := by
  classical
  rw [MvPolynomial.mem_ideal_span_X_image]
  intro m hm
  by_contra haux
  push_neg at haux
  have hdiff :
      MvPolynomial.coeff m
        (P - MvPolynomial.monomial (Finsupp.single t N) c) ≠ 0 :=
    MvPolynomial.mem_support_iff.mp hm
  by_cases hmt : m = Finsupp.single t N
  · subst m
    simp [hcoeff] at hdiff
  have hmono :
      MvPolynomial.coeff m
        (MvPolynomial.monomial (Finsupp.single t N) c) = 0 := by
    simp [MvPolynomial.coeff_monomial, Ne.symm hmt]
  have hmP : m ∈ P.support := by
    apply MvPolynomial.mem_support_iff.mpr
    simpa [hmono] using hdiff
  have hsupp : m.support ⊆ {t} := by
    intro i hi
    have hiVars : i ∈ P.vars :=
      (MvPolynomial.mem_vars i).mpr ⟨m, hmP, hi⟩
    have hiAllowed : i = t ∨ i ∈ s := by
      simpa only [Set.mem_insert_iff] using hvars hiVars
    rcases hiAllowed with rfl | his
    · simp
    · exact False.elim ((Finsupp.mem_support_iff.mp hi) (haux i his))
  have hmform : m = Finsupp.single t (m t) :=
    Finsupp.support_subset_singleton.mp hsupp
  have hdegree : m.degree = N := by
    rw [Finsupp.degree_eq_weight_one]
    exact hP (MvPolynomial.mem_support_iff.mp hmP)
  rw [hmform, Finsupp.degree_single] at hdegree
  exact hmt (by rw [hmform, hdegree])

/-- A prime containing a homogeneous relation, all auxiliary
variables, and a unit pure coefficient must contain the distinguished
variable. -/
theorem X_mem_of_homogeneous_mem_prime
    {P : MvPolynomial σ R} {N : ℕ} {t : σ} {s : Set σ} {c : R}
    (hP : P.IsHomogeneous N)
    (hvars : (P.vars : Set σ) ⊆ insert t s)
    (hcoeff : P.coeff (Finsupp.single t N) = c)
    (hc : IsUnit c)
    {p : Ideal (MvPolynomial σ R)} (hp : p.IsPrime)
    (hPmem : P ∈ p)
    (hsmem : ∀ i ∈ s, MvPolynomial.X i ∈ p) :
    MvPolynomial.X t ∈ p := by
  have hdiff :
      P - MvPolynomial.monomial (Finsupp.single t N) c ∈ p :=
    (Ideal.span_le.mpr (by
      rintro _ ⟨i, hi, rfl⟩
      exact hsmem i hi))
      (sub_pureMonomial_mem_span_X hP hvars hcoeff)
  have hmono : MvPolynomial.monomial (Finsupp.single t N) c ∈ p := by
    have := p.sub_mem hPmem hdiff
    simpa only [sub_sub_cancel] using this
  rw [← MvPolynomial.C_mul_X_pow_eq_monomial] at hmono
  have hC : IsUnit (MvPolynomial.C c : MvPolynomial σ R) :=
    hc.map (MvPolynomial.C : R →+* MvPolynomial σ R)
  have hpow : MvPolynomial.X t ^ N ∈ p :=
    (p.unit_mul_mem_iff_mem hC).mp hmono
  exact hp.mem_of_pow_mem N hpow

#print axioms sub_pureMonomial_mem_span_X
#print axioms X_mem_of_homogeneous_mem_prime

end AlgebraicAnalysis.MvPolynomial
